### ISSUE TITLE
install failes: No module named snxvpnversion

### ISSUE THREAD

**Issue by rhoerbe** [schlatterbeck/snxvpn#2]
python setup.py install --prefix=/usr/local
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    from snxvpnversion import VERSION
ImportError: No module named snxvpnversion

**Comment by schlatterbeck** [comment]
Fixed README.rst with detailed description how to install from source, using pip/pip3 is the preferred way now.

**Comment by mrzlanx532** [comment]
Makefile is missing from repository https://git.code.sf.net/p/sfreleasetools/code sfreleasetools-code
