### ISSUE TITLE
missing .netrc, .snxvpnrc

### ISSUE THREAD

**Issue by rhoerbe** [schlatterbeck/snxvpn#4]
workaround: touch, or fill as in:

cat << EOF > ~/.snxvpnrc
server snx.example.org
username john.doe
EOF

cat << EOF > ~/ .netrc
machine snx.example.org

  login john.doe
  password copy_this_password_do_never_change;-)

**Comment by schlatterbeck** [comment]
Fixed in one of the latests commits
